---
- name: Full Production-Grade Server Setup and Deployment
  hosts: tag_stage # ◄ Changed to match your Dynamic Inventory tag group
  become: true

  roles:
    - server_setup # ◄ Links to your custom execution role
